/******************************************************************************/
/****        Generated by IBExpert 2025.4.22.1 28/03/2026 14:57:44         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\SysDH\fbclient.dll';

CREATE DATABASE '127.0.0.1/3050:C:\Cheque\DADOS.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TB_CHEQUE (
    ID_CHEQUE               INTEGER GENERATED BY DEFAULT AS IDENTITY,
    CONTA_CHEQUE            INTEGER,
    NUMERO_CHEQUE           VARCHAR(15) NOT NULL,
    FORNECEDOR_CHEQUE       INTEGER,
    VALOR_CHEQUE            NUMERIC(18,2),
    DATA_VENCIMENTO_CHEQUE  DATE NOT NULL,
    DATA_COMPENSADO         DATE,
    ESTADO_CHEQUE           VARCHAR(14) NOT NULL,
    NOMINAL_CHEQUE          VARCHAR(100),
    DATA_CADASTRO           DATE,
    CHEQUE_OBSERVACAO       VARCHAR(50)
);

CREATE TABLE TB_CONTA (
    ID_CONTA      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NOME_CONTA    VARCHAR(100),
    NUMERO_CONTA  VARCHAR(30),
    AGENCIA       VARCHAR(20),
    BANCO         VARCHAR(60)
);

CREATE TABLE TB_FORNECEDOR (
    FOR_PESSOA             INTEGER NOT NULL,
    FOR_EMPRESA            INTEGER NOT NULL,
    FOR_EMAIL_COMPRA       VARCHAR(50),
    FOR_OBSERVACAO         VARCHAR(2000),
    FOR_DT_CADASTRO        DATE,
    FOR_MSG_ALERTA         VARCHAR(2000),
    FOR_REGIME             VARCHAR(1),
    FOR_EXPORTADOR         VARCHAR(60),
    FOR_COD_FABRICANTE     VARCHAR(60),
    FOR_ALIQUOTA_FUNRURAL  NUMERIC(15,6)
);

CREATE TABLE TB_PESSOA (
    PESS_ID    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    PESS_NOME  VARCHAR(120) NOT NULL
);



/******************************************************************************/
/****                       Autoincrement generators                       ****/
/******************************************************************************/

ALTER TABLE TB_CHEQUE ALTER ID_CHEQUE RESTART WITH 25;
ALTER TABLE TB_CONTA ALTER ID_CONTA RESTART WITH 24;
ALTER TABLE TB_PESSOA ALTER PESS_ID RESTART WITH 17;




/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE TB_CHEQUE ADD PRIMARY KEY (ID_CHEQUE);
ALTER TABLE TB_CONTA ADD PRIMARY KEY (ID_CONTA);
ALTER TABLE TB_PESSOA ADD PRIMARY KEY (PESS_ID);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE TB_CHEQUE ADD CONSTRAINT FK_CHE_PESSOA FOREIGN KEY (FORNECEDOR_CHEQUE) REFERENCES TB_PESSOA (PESS_ID);
ALTER TABLE TB_FORNECEDOR ADD CONSTRAINT FK_FOR_PESSOA FOREIGN KEY (FOR_PESSOA) REFERENCES TB_PESSOA (PESS_ID);
